services:
  osrm:
    image: osrm/osrm-backend:latest
    platform: linux/amd64
    volumes:
      - ./osm-data:/data 
    ports:
      - "5001:5000"
    command: >
      osrm-routed --algorithm mld --port 5000 /data/germany-latest.osrm

  app:
    image: gitlab.lrz.de:5005/ldv/teaching/ami/ami2025/projects/group06:latest
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - osrm
    ports:
      - "5050:5050"
    environment:
      - OSRM_URL=http://osrm:5000